export const siteConfig = {
  name: "Salman Ahmad | Developer Portfolio",
  authorName: "Salman Ahmad",
  username: "salmancrc",
  description:
    "Salman Ahmad's portfolio showcasing projects, skills, and experience as a Front-End Developer.",
  url: "https://salmanahmad.xyz",
  links: {
    twitter: "https://x.com/",
    github: "https://github.com/salmancrc",
  },
  ogImage: "https://salmanahmad.xyz/profile-pic.png",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/salman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/salman-logo.png",
  keywords: [
    "Salman Ahmad",
    "Front-End Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Front-End Developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
